"""Generate krkn-hub boilerplate files for new scenarios."""

import json
import logging
from pathlib import Path

from src.models import GapAnalysis

logger = logging.getLogger(__name__)


def generate_hub_files(
    gap: GapAnalysis,
    scenario_name: str,
    env_vars: dict[str, str],
) -> dict[str, str]:
    """Generate all krkn-hub files for a new scenario.

    Args:
        gap: The gap analysis
        scenario_name: Kebab-case name (e.g., "etcd-throttling")
        env_vars: Dict of env var name → default value

    Returns:
        Dict of relative_path → file_content
    """
    display_name = scenario_name.replace("-", " ").title()
    scenario_type = scenario_name.replace("-", "_") + "_scenarios"
    bug = gap.bug

    files = {}

    # env.sh
    env_lines = ["#!/bin/bash"]
    for var, default in env_vars.items():
        env_lines.append(f'export {var}=${{{var}:="{default}"}}')
    env_lines.append("")
    env_lines.append(f"export SCENARIO_TYPE=${{{scenario_type.upper()}:={scenario_type}}}")
    env_lines.append(f'export SCENARIO_FILE=${{SCENARIO_FILE:="$KRAKEN_FOLDER/scenarios/{scenario_name}.yaml"}}')
    files[f"{scenario_name}/env.sh"] = "\n".join(env_lines) + "\n"

    # run.sh
    files[f"{scenario_name}/run.sh"] = f"""#!/bin/bash
ROOT_FOLDER="/home/krkn"
KRAKEN_FOLDER="$ROOT_FOLDER/kraken"

# Source env.sh to read all the vars
source $ROOT_FOLDER/main_env.sh
source $ROOT_FOLDER/env.sh
source $ROOT_FOLDER/common_run.sh
extra_var=""
if [[ $KRKN_DEBUG == "True" ]];then
  set -ex
  extra_var="--debug True"
fi

# Build scenario config from environment variables
python3.11 $ROOT_FOLDER/build_config_file.py --outconfig $KRAKEN_FOLDER/scenarios/{scenario_name}.yaml
envsubst < $KRAKEN_FOLDER/config/config.yaml.template > $KRAKEN_FOLDER/config/{scenario_name}_config.yaml

cat $KRAKEN_FOLDER/config/{scenario_name}_config.yaml
cat $KRAKEN_FOLDER/scenarios/{scenario_name}.yaml

checks

# Run Kraken
cd $KRAKEN_FOLDER
python3.11 run_kraken.py --config=config/{scenario_name}_config.yaml $extra_var
"""

    # build_config_file.py
    config_lines = [
        "import logging",
        "import os",
        "import yaml",
        "import argparse",
        "",
        "",
        "def main():",
        "    parser = argparse.ArgumentParser(description='')",
        "    parser.add_argument('--outconfig', type=str, help='Output config path')",
        "    args = parser.parse_args()",
        "",
    ]
    for var, default in env_vars.items():
        config_lines.append(f'    {var.lower()} = os.getenv("{var}", "{default}")')
    config_lines.append("")
    config_lines.append(f'    config = [{{')
    config_lines.append(f'        "{scenario_type.rstrip("s")}": {{')
    for var in env_vars:
        val_expr = var.lower()
        # Try to convert numeric values
        if env_vars[var].isdigit():
            val_expr = f"int({var.lower()})"
        elif env_vars[var].lower() in ("true", "false"):
            val_expr = f'{var.lower()}.lower() == "true"'
        config_lines.append(f'            "{var.lower()}": {val_expr},')
    config_lines.append(f'        }}')
    config_lines.append(f'    }}]')
    config_lines.append("")
    config_lines.append('    with open(args.outconfig, "w") as out:')
    config_lines.append('        yaml.dump(config, out, default_flow_style=False)')
    config_lines.append("")
    config_lines.append("")
    config_lines.append("if __name__ == '__main__':")
    config_lines.append("    main()")
    files[f"{scenario_name}/build_config_file.py"] = "\n".join(config_lines) + "\n"

    # Dockerfile.template
    files[f"{scenario_name}/Dockerfile.template"] = f"""# Dockerfile for {display_name} chaos scenario
# Generated by krkn-chaos-coordinator for {bug.key}

FROM quay.io/krkn-chaos/krkn:latest

ENV KUBECONFIG /home/krkn/.kube/config

COPY config.yaml.template /home/krkn/kraken/config/config.yaml.template
COPY {scenario_name}/env.sh /home/krkn/env.sh
COPY {scenario_name}/build_config_file.py /home/krkn/build_config_file.py
COPY env.sh /home/krkn/main_env.sh
COPY {scenario_name}/run.sh /home/krkn/run.sh
COPY common_run.sh /home/krkn/common_run.sh

LABEL krknctl.title="{display_name}"
LABEL krknctl.description="{display_name} chaos scenario for {bug.component}. {bug.summary[:100]}"

LABEL krknctl.input_fields='$KRKNCTL_INPUT'

ENTRYPOINT /home/krkn/kraken/containers/setup-ssh.sh && /home/krkn/run.sh
"""

    # krknctl-input.json
    inputs = []
    for var, default in env_vars.items():
        name = var.lower().replace("_", "-")
        inputs.append({
            "name": name,
            "short_description": var.replace("_", " ").title(),
            "description": f"Configuration for {var}",
            "variable": var,
            "type": "number" if default.isdigit() else "string",
            "default": default,
            "required": "false",
        })
    files[f"{scenario_name}/krknctl-input.json"] = json.dumps(inputs, indent=2) + "\n"

    # README.md
    files[f"{scenario_name}/README.md"] = f"""# {display_name} Scenario

Generated by krkn-chaos-coordinator for [{bug.key}]({bug.url}).

See [doc](../docs/{scenario_name}.md) for how to run and all variables.
"""

    # docs/<name>.md
    param_rows = []
    for var, default in env_vars.items():
        param_rows.append(f"|{var}| Configuration for {var} |{default}|")
    param_table = "\n".join(param_rows)

    files[f"docs/{scenario_name}.md"] = f"""### {display_name} Scenario

{bug.summary}

For more details, see [{bug.key}]({bug.url}).

#### Run

```
$ podman run --name={scenario_name} --net=host --env-host=true \\
  -v <path-to-kube-config>:/home/krkn/.kube/config:Z \\
  -d quay.io/krkn-chaos/krkn-hub:{scenario_name}
```

#### Supported Parameters

|Parameter | Description | Default |
|----------|-------------|---------|
{param_table}
"""

    logger.info("Generated %d krkn-hub files for %s", len(files), scenario_name)
    return files
