"""Create draft PRs on GitHub forks for chaos scenario changes."""

from __future__ import annotations

import logging
import os
import subprocess
from pathlib import Path
from urllib.parse import urlparse

from dotenv import load_dotenv

from src.agents.act import _infer_injection_method, _scenario_type_from_plugin
from src.apis.github_client import GitHubClient
from src.models import GapAnalysis

load_dotenv()

logger = logging.getLogger(__name__)

_krkn_repo_url = os.environ.get("KRKN_REPO_URL", "https://github.com/krkn-chaos/krkn")
_url_parts = urlparse(_krkn_repo_url).path.strip("/").split("/")
UPSTREAM_OWNER = _url_parts[0] if len(_url_parts) >= 1 else "krkn-chaos"
_UPSTREAM_REPO = _url_parts[1] if len(_url_parts) >= 2 else "krkn"

# Local fork paths
FORK_PATHS = {
    "krkn": Path(os.environ.get("KRKN_REPO_PATH", str(Path.home() / "krkn"))),
    "krkn-hub": Path.home() / "krkn-hub",
    "website": Path.home() / "website",
    "release": Path.home() / "release",
}

FORK_OWNER = os.environ.get("GITHUB_FORK_OWNER", "krkn-chaos")


def _run_git(repo_path: Path, *args: str) -> tuple[int, str]:
    """Run a git command in a repo directory."""
    cmd = ["git", "-C", str(repo_path)] + list(args)
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    return result.returncode, result.stdout.strip() + result.stderr.strip()


def _create_branch(repo_path: Path, branch_name: str) -> bool:
    """Create a new branch from upstream main."""
    # Fetch upstream
    code, out = _run_git(repo_path, "fetch", "upstream", "main")
    if code != 0:
        logger.error("Failed to fetch upstream: %s", out)
        return False

    # Create branch from upstream/main
    code, out = _run_git(repo_path, "checkout", "-b", branch_name, "upstream/main")
    if code != 0:
        # Branch might already exist
        code, out = _run_git(repo_path, "checkout", branch_name)
        if code != 0:
            logger.error("Failed to create/checkout branch %s: %s", branch_name, out)
            return False

    return True


def _write_file(repo_path: Path, file_path: str, content: str) -> bool:
    """Write a file in the repo."""
    full_path = repo_path / file_path
    full_path.parent.mkdir(parents=True, exist_ok=True)
    full_path.write_text(content)
    return True


def _commit_and_push(repo_path: Path, branch_name: str, message: str, files: list[str]) -> bool:
    """Stage files, commit, and push to origin."""
    for f in files:
        _run_git(repo_path, "add", f)

    code, out = _run_git(repo_path, "commit", "-m", message)
    if code != 0:
        logger.error("Failed to commit: %s", out)
        return False

    code, out = _run_git(repo_path, "push", "-u", "origin", branch_name)
    if code != 0:
        logger.error("Failed to push: %s", out)
        return False

    return True


def _cleanup_branch(repo_path: Path) -> None:
    """Switch back to main branch."""
    _run_git(repo_path, "checkout", "main")


def create_scenario_pr(
    github: GitHubClient,
    gap: GapAnalysis,
    scenario_yaml: str,
    scenario_filename: str,
    dry_run: bool = True,
) -> dict | None:
    """Create a PR on krkn-chaos/krkn with a new/modified scenario YAML.

    Args:
        github: GitHub client
        gap: The gap analysis that triggered this PR
        scenario_yaml: The YAML content for the scenario
        scenario_filename: Filename under scenarios/openshift/ (e.g., etcd_throttling.yaml)
        dry_run: If True, show what would be done without creating

    Returns:
        PR dict or None
    """
    repo_path = FORK_PATHS["krkn"]
    branch_name = f"chaos-coordinator/{gap.bug.key.lower()}"
    scenario_path = f"scenarios/openshift/{scenario_filename}"

    if dry_run:
        logger.info("DRY RUN — would create PR:")
        logger.info("  Repo: %s/%s -> %s/%s", FORK_OWNER, "krkn", UPSTREAM_OWNER, "krkn")
        logger.info("  Branch: %s", branch_name)
        logger.info("  File: %s", scenario_path)
        return {"dry_run": True, "branch": branch_name, "file": scenario_path}

    if not repo_path.exists():
        logger.error("krkn repo not found at %s", repo_path)
        return None

    # Create branch
    if not _create_branch(repo_path, branch_name):
        return None

    try:
        # Write scenario file
        _write_file(repo_path, scenario_path, scenario_yaml)

        # Commit and push
        commit_msg = (
            f"feat: add chaos scenario for {gap.bug.key}\n\n"
            f"Bug: {gap.bug.url}\n"
            f"Failure mode: {gap.bug.summary}\n"
            f"Generated by krkn-chaos-coordinator"
        )
        if not _commit_and_push(repo_path, branch_name, commit_msg, [scenario_path]):
            return None

        # Create PR via GitHub API
        pr_title = f"[chaos-coordinator] {gap.bug.key}: Add chaos scenario"
        pr_body = (
            f"## Auto-generated Chaos Scenario\n\n"
            f"**Bug:** [{gap.bug.key}]({gap.bug.url})\n"
            f"**Component:** {gap.bug.component}\n"
            f"**Failure Mode:** {gap.bug.summary}\n\n"
            f"### Changes\n\n"
            f"- Added `{scenario_path}`\n\n"
            f"### Confidence\n\n"
            f"{gap.reasoning}\n\n"
            f"---\n"
            f"*Generated by krkn-chaos-coordinator*"
        )

        url = f"https://api.github.com/repos/{UPSTREAM_OWNER}/{_UPSTREAM_REPO}/pulls"
        payload = {
            "title": pr_title,
            "body": pr_body,
            "head": f"{FORK_OWNER}:{branch_name}",
            "base": "main",
            "draft": True,
        }

        try:
            response = github._session.post(url, json=payload, timeout=30)
            response.raise_for_status()
            pr = response.json()
            logger.info("Created PR: %s", pr.get("html_url"))
            return pr
        except Exception as e:
            logger.error("Failed to create PR: %s", e)
            return None

    finally:
        _cleanup_branch(repo_path)


def generate_scenario_yaml(gap: GapAnalysis) -> tuple[str, str]:
    """Generate a scenario YAML file content based on the gap analysis.

    Returns (yaml_content, filename).
    """
    bug = gap.bug
    component = bug.component.lower().replace(" ", "_").replace("/", "_")
    bug_id = bug.key.lower().replace("-", "_")
    filename = f"{component}_{bug_id}.yaml"

    _, plugin, _ = _infer_injection_method(gap)
    scenario_type = _scenario_type_from_plugin(plugin)

    namespace = "openshift-etcd" if "etcd" in component else f"openshift-{component}"

    header = f"""# Chaos scenario for {bug.key}: {bug.summary}
# Generated by krkn-chaos-coordinator
# Bug: {bug.url}
# Krkn chaos scenario type: {scenario_type}
#
"""

    # Generate YAML based on scenario type (structure matches krkn/scenarios examples)
    if scenario_type == "hog_scenarios":
        yaml_content = header + f"""# CPU hog — see scenarios/kube/cpu-hog.yml
duration: 300
workers: ''
hog-type: cpu
image: quay.io/krkn-chaos/krkn-hog
namespace: default
cpu-load-percentage: 90
cpu-method: all
node-selector: "node-role.kubernetes.io/master="
number-of-nodes: 1
taints: []
"""
    elif scenario_type == "node_scenarios":
        yaml_content = header + """# Node stop/start — see scenarios/openshift/aws_node_scenarios.yml
node_scenarios:
  - actions:
    - node_stop_start_scenario
    node_name:
    label_selector: node-role.kubernetes.io/master
    instance_count: 1
    runs: 1
    timeout: 360
    duration: 60
    cloud_type: aws
    parallel: true
    kube_check: true
    poll_interval: 15
"""
    elif scenario_type == "network_chaos_scenarios":
        yaml_content = header + f"""# Node network chaos — see scenarios/openshift/network_chaos.yaml
network_chaos:
  duration: 300
  node_name:
  label_selector: node-role.kubernetes.io/master
  instance_count: 1
  interfaces:
    - "<interface_name>"
  execution: serial
  egress:
    latency: 200ms
    loss: '0.05'
"""
    elif scenario_type == "network_chaos_ng_scenarios":
        yaml_content = header + f"""# Pod/network filter chaos — see scenarios/kube/pod-network-chaos.yml
- id: pod_network_chaos
  image: quay.io/krkn-chaos/krkn-network-chaos:latest
  wait_duration: 300
  test_duration: 120
  label_selector: app={component}
  service_account: ""
  taints: []
  namespace: '{namespace}'
  instance_count: 1
  target: "<pod_name>"
  execution: parallel
  interfaces: []
  ingress: true
  egress: true
  latency: 200ms
  loss: 10
  bandwidth: 1gbit
"""
    elif scenario_type == "application_outages_scenarios":
        yaml_content = header + f"""# Application route outage — see scenarios/openshift/app_outage.yaml
application_outage:
  duration: 600
  namespace: {namespace}
  pod_selector: {{app: {component}}}
  block: [Ingress, Egress]
  exclude_label: ""
"""
    elif scenario_type == "container_scenarios":
        yaml_content = header + f"""# Container kill — see scenarios/openshift/container_etcd.yml
scenarios:
- name: "kill {component} container"
  namespace: "{namespace}"
  label_selector: "app={component}"
  container_name: ""
  action: 1
  count: 1
  expected_recovery_time: 120
  exclude_label: ""
"""
    elif scenario_type == "http_load_scenarios":
        yaml_content = header + f"""# HTTP load — see scenarios/kube/http_load_scenario.yml
- http_load_scenario:
    runs: 1
    number-of-pods: 2
    namespace: default
    image: quay.io/krkn-chaos/krkn-http-load:latest
    attacker-nodes:
      node-role.kubernetes.io/worker:
        - ""
    targets:
      endpoints:
        - url: "https://your-service.example.com/health"
          method: "GET"
    rate: "50/1s"
    duration: "30s"
    workers: 10
    max_workers: 100
    connections: 100
    timeout: "10s"
    keepalive: true
    http2: true
    insecure: false
"""
    elif scenario_type == "kubevirt_vm_outage":
        yaml_content = header + f"""# KubeVirt VM outage — see scenarios/kubevirt/kubevirt-vm-outage.yaml
scenarios:
  - name: "kubevirt outage test"
    scenario: kubevirt_vm_outage
    parameters:
      vm_name: <vm-name>
      label_selector: ""
      namespace: {namespace}
      timeout: 60
"""
    elif scenario_type == "managedcluster_scenarios":
        yaml_content = header + """# ManagedCluster chaos — see scenarios/kube/managedcluster_scenarios_example.yml
managedcluster_scenarios:
  - actions:
    - managedcluster_stop_start_scenario
    managedcluster_name:
    instance_count: 1
    runs: 1
    timeout: 420
"""
    elif scenario_type == "pvc_scenarios":
        yaml_content = header + f"""# PVC fill — see scenarios/openshift/pvc_scenario.yaml
pvc_scenario:
  pvc_name: <pvc_name>
  pod_name: <pod_name>
  namespace: {namespace}
  fill_percentage: 50
  duration: 60
  block_size: 102400
"""
    elif scenario_type == "service_disruption_scenarios":
        yaml_content = header + f"""# Service disruption — see scenarios/openshift/ingress_namespace.yaml
scenarios:
- namespace: "^{namespace}$"
  runs: 1
  sleep: 15
  wait_time: 300
"""
    elif scenario_type == "service_hijacking_scenarios":
        yaml_content = header + f"""# Service hijacking — see scenarios/kube/service_hijacking.yaml
service_target_port: http-web-svc
service_name: {component}
service_namespace: {namespace}
image: quay.io/krkn-chaos/krkn-service-hijacking:v0.1.3
chaos_duration: 30
privileged: True
plan:
  - resource: "/health"
    steps:
      GET:
        - duration: 15
          status: 500
          mime_type: "application/json"
          payload: |
            {{
              "status":"internal server error"
            }}
"""
    elif scenario_type == "cluster_shut_down_scenarios":
        yaml_content = header + """# Cluster shut down — see scenarios/openshift/cluster_shut_down_scenario.yml
cluster_shut_down_scenario:
  runs: 1
  shut_down_duration: 150
  cloud_type: aws
  timeout: 60
"""
    elif scenario_type == "storage_throttle_scenarios":
        yaml_content = header + f"""# Storage throttle — see scenarios/openshift/storage_throttle.yaml
storage_throttle_scenario:
  pvc_name: <pvc_name>
  pod_name: <pod_name>
  namespace: {namespace}
  mount_path: ""
  throttle_type: bandwidth
  read_iops: 100
  write_iops: 50
  read_bps: 1048576
  write_bps: 524288
  duration: 120
  image: quay.io/krkn-chaos/krkn:tools
"""
    elif scenario_type == "syn_flood_scenarios":
        yaml_content = header + f"""# SYN flood — see scenarios/kube/syn_flood.yaml
packet-size: 120
window-size: 64
duration: 120
namespace: {namespace}
target-service: {component}
target-port: 443
target-service-label: ""
number-of-pods: 2
image: quay.io/krkn-chaos/krkn-syn-flood:v1.0.0
attacker-nodes:
  node-role.kubernetes.io/worker:
    - ""
"""
    elif scenario_type == "time_scenarios":
        yaml_content = header + f"""# Time skew — see scenarios/openshift/time_scenarios_example.yml
time_scenarios:
  - action: skew_time
    object_type: pod
    namespace: {namespace}
    container_name: ""
    label_selector: app={component}
"""
    elif scenario_type == "zone_outages_scenarios":
        yaml_content = header + """# Zone outage — see scenarios/openshift/zone_outage.yaml
zone_outage:
  cloud_type: aws
  duration: 600
  vpc_id:
  subnet_id: [subnet1, subnet2]
  default_acl_id:
"""
    elif scenario_type == "pod_disruption_scenarios":
        label_selector = "k8s-app=etcd" if "etcd" in component else f"app={component}"
        yaml_content = header + f"""# Pod kill — see scenarios/openshift/etcd.yml
- id: kill-pods
  config:
    namespace_pattern: ^{namespace}$
    label_selector: {label_selector}
    kill: 1
    krkn_pod_recovery_time: 120
    exclude_label: ""
"""
    else:
        # Default: pod disruption
        label_selector = "k8s-app=etcd" if "etcd" in component else f"app={component}"
        yaml_content = header + f"""# Pod kill — see scenarios/openshift/etcd.yml
- id: kill-pods
  config:
    namespace_pattern: ^{namespace}$
    label_selector: {label_selector}
    kill: 1
    krkn_pod_recovery_time: 120
    exclude_label: ""
"""

    return yaml_content, filename
