"""Tests for draft PR scenario YAML generation."""

from pathlib import Path

import pytest

from src.agents.pr_creator import (
    collect_related_scenario_templates,
    create_scenario_pr,
    generate_scenario_candidates,
    generate_scenario_yaml,
)
from src.models import Bug, GapAnalysis


def _bug(summary: str, component: str = "Etcd") -> Bug:
    return Bug(
        key="OCPBUGS-9999",
        summary=summary,
        description="",
        component=component,
        priority="Major",
        status="New",
        created="2026-01-01",
        url="https://issues.redhat.com/browse/OCPBUGS-9999",
    )


@pytest.fixture
def krkn(tmp_path: Path) -> Path:
    """Minimal krkn repo with a few scenario templates."""
    (tmp_path / "scenarios" / "openshift").mkdir(parents=True)
    (tmp_path / "scenarios" / "kube").mkdir(parents=True)
    (tmp_path / "scenarios" / "openshift" / "etcd.yml").write_text(
        "- id: kill-pods\n  config:\n    namespace_pattern: ^openshift-etcd$\n"
        "    label_selector: k8s-app=etcd\n    kill: 1\n"
    )
    (tmp_path / "scenarios" / "openshift" / "container_etcd.yml").write_text(
        "scenarios:\n- name: kill etcd container\n  namespace: openshift-etcd\n"
        "  label_selector: k8s-app=etcd\n  action: 1\n"
    )
    (tmp_path / "scenarios" / "kube" / "cpu-hog.yml").write_text(
        "duration: 10\nhog-type: cpu\ncpu-load-percentage: 90\n"
    )
    (tmp_path / "scenarios" / "openshift" / "network_chaos.yaml").write_text(
        "network_chaos:\n  duration: 300\n  label_selector: master\n"
    )
    return tmp_path


class TestGenerateScenarioCandidates:
    def test_map_base_scenario_includes_siblings(self, krkn: Path):
        gap = GapAnalysis(
            bug=_bug("etcd crash under load"),
            base_scenario="scenarios/openshift/etcd.yml",
        )
        candidates = generate_scenario_candidates(gap, krkn_path=krkn)

        assert len(candidates) >= 2
        paths = [p for p, _ in candidates]
        assert all("OCPBUGS-9999-candidate-" in p for p in paths)
        assert all(p.startswith("scenarios/openshift/") for p in paths)

        templates = collect_related_scenario_templates(gap, krkn_path=krkn)
        assert templates[0][2] == "scenarios/openshift/etcd.yml"

        for _path, content in candidates:
            assert "Generated by krkn-chaos-coordinator" in content
            assert "MAP phase match" in content
            assert "MAP base scenario:" in content
            assert "Source template:" in content

    def test_output_path_preserves_source_directory(self, krkn: Path):
        gap = GapAnalysis(
            bug=_bug("cpu pressure on masters"),
            base_scenario="scenarios/kube/cpu-hog.yml",
        )
        candidates = generate_scenario_candidates(gap, krkn_path=krkn)
        assert candidates
        assert candidates[0][0].startswith("scenarios/kube/")
        assert "OCPBUGS-9999-candidate-cpu-hog.yaml" in candidates[0][0]

    def test_base_scenario_prioritized(self, krkn: Path):
        gap = GapAnalysis(
            bug=_bug("etcd issue"),
            base_scenario="scenarios/openshift/container_etcd.yml",
        )
        templates = collect_related_scenario_templates(gap, krkn_path=krkn)
        assert templates[0][2] == "scenarios/openshift/container_etcd.yml"

    def test_no_map_match_returns_no_candidates(self, krkn: Path):
        gap = GapAnalysis(bug=_bug("api server throttling under resource pressure"))
        assert generate_scenario_candidates(gap, krkn_path=krkn) == []
        assert collect_related_scenario_templates(gap, krkn_path=krkn) == []

    def test_no_map_match_stub_explains_skip(self, krkn: Path):
        gap = GapAnalysis(bug=_bug("network partition causes ingress latency"))
        content, filename = generate_scenario_yaml(gap, krkn_path=krkn)
        assert filename.endswith("-candidate-stub.yaml")
        assert "No MAP match" in content
        assert "base_scenario is unset" in content

    def test_missing_base_still_uses_siblings(self, krkn: Path):
        """If MAP path is missing locally but siblings exist, use those."""
        gap = GapAnalysis(
            bug=_bug("etcd crash"),
            base_scenario="scenarios/openshift/does-not-exist.yml",
        )
        candidates = generate_scenario_candidates(gap, krkn_path=krkn)
        assert candidates
        assert "does-not-exist" not in candidates[0][0]

    def test_missing_local_template_stub(self, krkn: Path):
        gap = GapAnalysis(
            bug=_bug("etcd crash"),
            base_scenario="scenarios/nowhere/missing.yml",
        )
        content, filename = generate_scenario_yaml(gap, krkn_path=krkn)
        assert filename.endswith("-candidate-stub.yaml")
        assert "not found under KRKN_REPO_PATH" in content

    def test_generate_scenario_yaml_returns_first_candidate(self, krkn: Path):
        gap = GapAnalysis(
            bug=_bug("etcd crash"),
            base_scenario="scenarios/openshift/etcd.yml",
        )
        content, filename = generate_scenario_yaml(gap, krkn_path=krkn)

        assert filename.startswith("OCPBUGS-9999-candidate-")
        assert "kill-pods" in content or "label_selector" in content

    def test_max_candidates_cap(self, krkn: Path):
        gap = GapAnalysis(
            bug=_bug("etcd crash"),
            base_scenario="scenarios/openshift/etcd.yml",
        )
        candidates = generate_scenario_candidates(
            gap, krkn_path=krkn, max_candidates=1,
        )
        assert len(candidates) == 1

    def test_create_scenario_pr_skips_without_map_match(self):
        gap = GapAnalysis(bug=_bug("unrelated failure"))
        result = create_scenario_pr(github=None, gap=gap, dry_run=True)
        assert result is None
