"""Tests for draft PR scenario YAML generation."""

from pathlib import Path
from unittest.mock import patch

import pytest

from src.agents.act import PLUGIN_REGISTRY, _plugin_path, _scenario_type_from_plugin
from src.agents.pr_creator import (
    collect_related_scenario_templates,
    generate_scenario_candidates,
    generate_scenario_yaml,
)
from src.models import Bug, GapAnalysis


def _bug(summary: str, component: str = "Etcd") -> Bug:
    return Bug(
        key="OCPBUGS-9999",
        summary=summary,
        description="",
        component=component,
        priority="Major",
        status="New",
        created="2026-01-01",
        url="https://issues.redhat.com/browse/OCPBUGS-9999",
    )


@pytest.fixture
def mini_krkn(tmp_path: Path) -> Path:
    """Minimal krkn repo with a few scenario templates."""
    (tmp_path / "scenarios" / "openshift").mkdir(parents=True)
    (tmp_path / "scenarios" / "kube").mkdir(parents=True)
    (tmp_path / "scenarios" / "openshift" / "etcd.yml").write_text(
        "- id: kill-pods\n  config:\n    namespace_pattern: ^openshift-etcd$\n"
        "    label_selector: k8s-app=etcd\n    kill: 1\n"
    )
    (tmp_path / "scenarios" / "openshift" / "container_etcd.yml").write_text(
        "scenarios:\n- name: kill etcd container\n  namespace: openshift-etcd\n"
        "  label_selector: k8s-app=etcd\n  action: 1\n"
    )
    (tmp_path / "scenarios" / "kube" / "cpu-hog.yml").write_text(
        "duration: 10\nhog-type: cpu\ncpu-load-percentage: 90\n"
    )
    (tmp_path / "scenarios" / "openshift" / "network_chaos.yaml").write_text(
        "network_chaos:\n  duration: 300\n  label_selector: master\n"
    )
    return tmp_path


class TestGenerateScenarioCandidates:
    def test_map_base_scenario_includes_siblings(self, mini_krkn: Path):
        gap = GapAnalysis(
            bug=_bug("etcd crash under load"),
            base_scenario="scenarios/openshift/etcd.yml",
        )
        candidates = generate_scenario_candidates(gap, krkn_path=mini_krkn)

        assert len(candidates) >= 2
        paths = [p for p, _ in candidates]
        assert all("OCPBUGS-9999-candidate-" in p for p in paths)
        assert all(p.startswith("scenarios/openshift/") for p in paths)

        templates = collect_related_scenario_templates(gap, krkn_path=mini_krkn)
        assert templates[0][2] == "scenarios/openshift/etcd.yml"

        for _path, content in candidates:
            assert "Generated by krkn-chaos-coordinator" in content
            assert "MAP phase match" in content
            assert "MAP base scenario:" in content
            assert "Source template:" in content

    def test_map_match_does_not_call_keyword_inference(self, mini_krkn: Path):
        gap = GapAnalysis(
            bug=_bug("network partition"),
            base_scenario="scenarios/openshift/etcd.yml",
        )
        with patch("src.agents.pr_creator._infer_injection_method") as mock_infer:
            candidates = generate_scenario_candidates(gap, krkn_path=mini_krkn)

        mock_infer.assert_not_called()
        assert "kill-pods" in candidates[0][1]

    def test_base_scenario_prioritized(self, mini_krkn: Path):
        gap = GapAnalysis(
            bug=_bug("etcd issue"),
            base_scenario="scenarios/openshift/container_etcd.yml",
        )
        templates = collect_related_scenario_templates(gap, krkn_path=mini_krkn)
        assert templates[0][2] == "scenarios/openshift/container_etcd.yml"

    def test_hog_scenario_via_fallback_inference(self, mini_krkn: Path):
        gap = GapAnalysis(
            bug=_bug("api server throttling under resource pressure on masters")
        )
        candidates = generate_scenario_candidates(gap, krkn_path=mini_krkn)
        assert candidates
        assert "keyword fallback" in candidates[0][1]
        assert "hog-type: cpu" in candidates[0][1]

    def test_network_scenario_via_fallback_inference(self, mini_krkn: Path):
        gap = GapAnalysis(bug=_bug("network partition causes ingress latency"))
        candidates = generate_scenario_candidates(gap, krkn_path=mini_krkn)
        assert candidates
        assert "keyword fallback" in candidates[0][1]
        assert "network_chaos" in candidates[0][1]

    def test_generate_scenario_yaml_returns_first_candidate(self, mini_krkn: Path):
        gap = GapAnalysis(
            bug=_bug("etcd crash"),
            base_scenario="scenarios/openshift/etcd.yml",
        )
        content, filename = generate_scenario_yaml(gap, krkn_path=mini_krkn)

        assert filename.startswith("OCPBUGS-9999-candidate-")
        assert "kill-pods" in content or "label_selector" in content

    @pytest.mark.parametrize("plugin_dir,scenario_type", PLUGIN_REGISTRY.items())
    def test_each_registry_type_generates_output(
        self, plugin_dir: str, scenario_type: str, mini_krkn: Path
    ):
        gap = GapAnalysis(bug=_bug("test"))
        with patch(
            "src.agents.pr_creator._infer_injection_method",
            return_value=("method", _plugin_path(plugin_dir), "hint"),
        ):
            content, filename = generate_scenario_yaml(gap, krkn_path=mini_krkn)

        assert filename.endswith(".yaml")
        assert "OCPBUGS-9999-candidate-" in filename
        assert "Generated by krkn-chaos-coordinator" in content
        if scenario_type in {
            "hog_scenarios",
            "pod_disruption_scenarios",
            "network_chaos_scenarios",
            "container_scenarios",
        }:
            assert "Source template:" in content
        else:
            assert "No matching templates" in content

    def test_unknown_plugin_path_falls_back_to_pod_disruption(self):
        assert _scenario_type_from_plugin(_plugin_path("unknown_plugin")) == "pod_disruption_scenarios"

    def test_fallback_ranks_matching_template(self, mini_krkn: Path):
        gap = GapAnalysis(
            bug=_bug("container restart loop in etcd pod", component="Etcd"),
        )
        with patch(
            "src.agents.pr_creator._infer_injection_method",
            return_value=("method", _plugin_path("pod_disruption"), "hint"),
        ):
            templates = collect_related_scenario_templates(gap, krkn_path=mini_krkn)

        assert templates[0][2] == "scenarios/openshift/container_etcd.yml"

    def test_max_candidates_cap(self, mini_krkn: Path):
        gap = GapAnalysis(
            bug=_bug("etcd crash"),
            base_scenario="scenarios/openshift/etcd.yml",
        )
        candidates = generate_scenario_candidates(
            gap, krkn_path=mini_krkn, max_candidates=1,
        )
        assert len(candidates) == 1
