"""Tests for draft PR scenario YAML generation."""

from unittest.mock import patch

import pytest

from src.agents.act import PLUGIN_REGISTRY, _plugin_path, _scenario_type_from_plugin
from src.agents.pr_creator import generate_scenario_yaml
from src.models import Bug, GapAnalysis


def _bug(summary: str, component: str = "etcd") -> Bug:
    return Bug(
        key="OCPBUGS-9999",
        summary=summary,
        description="",
        component=component,
        priority="Major",
        status="New",
        created="2026-01-01",
        url="https://issues.redhat.com/browse/OCPBUGS-9999",
    )


class TestGenerateScenarioYaml:
    @pytest.mark.parametrize("plugin_dir,scenario_type", PLUGIN_REGISTRY.items())
    def test_each_registry_scenario_type_generates_yaml(
        self, plugin_dir: str, scenario_type: str
    ):
        gap = GapAnalysis(bug=_bug("test"))
        with patch(
            "src.agents.pr_creator._infer_injection_method",
            return_value=("method", _plugin_path(plugin_dir), "hint"),
        ):
            yaml_content, filename = generate_scenario_yaml(gap)

        assert filename.endswith(".yaml")
        assert "Generated by krkn-chaos-coordinator" in yaml_content
        text = yaml_content.lower()
        key_fragment = scenario_type.replace("_scenarios", "")
        assert (
            scenario_type in yaml_content
            or key_fragment in text
            or key_fragment.replace("_", " ") in text
            or "kill:" in yaml_content
        )

    def test_hog_scenario_via_inference(self):
        gap = GapAnalysis(
            bug=_bug("api server throttling under resource pressure on masters")
        )
        yaml_content, _ = generate_scenario_yaml(gap)
        assert "hog-type: cpu" in yaml_content
        assert "cpu-load-percentage" in yaml_content

    def test_network_scenario_via_inference(self):
        gap = GapAnalysis(bug=_bug("network partition causes ingress latency"))
        yaml_content, _ = generate_scenario_yaml(gap)
        assert "network_chaos" in yaml_content

    def test_unknown_plugin_path_falls_back_to_pod_disruption(self):
        assert _scenario_type_from_plugin(_plugin_path("unknown_plugin")) == "pod_disruption_scenarios"
